name: Deploy Foundation

on:
  push:
    paths: 'foundation/**'

jobs:
  deployFoundationFrankfurt:
    name: Deploy Foundation Frankfurt
    runs-on: ubuntu-latest
    environment: frankfurt
    concurrency:
      group: EnvGame-foundation-frankfurt
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      
      - run: npm install
        working-directory: foundation

      - uses: pulumi/actions@v3
        with:
          command: up
          work-dir: foundation
          comment-on-pr: false
          stack-name: frankfurt
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
  
  deployFoundationIreland:
    name: Deploy Foundation Ireland
    runs-on: ubuntu-latest
    environment: ireland
    concurrency:
      group: EnvGame-foundation-ireland
      cancel-in-progress: false
    needs: deployFoundationFrankfurt
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      
      - run: npm install
        working-directory: foundation

      - uses: pulumi/actions@v3
        with:
          command: up
          work-dir: foundation
          comment-on-pr: false
          stack-name: ireland
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}